# Generated by Django 3.2.4 on 2023-02-05 10:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE_LAYER', '0002_auto_20230205_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUSTOMER_PHARMACIST_ALERT_MODEL',
            fields=[
                ('CUSTOMERPHARMACIST_INDEX_KEY', models.AutoField(primary_key=True, serialize=False)),
                ('CUSTOMERPHARMACIST_KEYWORD', models.CharField(blank=True, max_length=400, null=True)),
                ('CUSTOMERPHARMACIST_LAT', models.CharField(blank=True, max_length=400, null=True)),
                ('CUSTOMERPHARMACIST_LONG', models.CharField(blank=True, max_length=400, null=True)),
                ('CUSTOMERPHARMACIST_Create_Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('CUSTOMERPHARMACIST_Update_Date', models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 47, 29, 88419, tzinfo=utc), editable=False)),
                ('CUSTOMERPHARMACIST_isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CUSTOMER_PHARMACIST_ALERT_MODEL',
            },
        ),
        migrations.AlterField(
            model_name='admin_user_model',
            name='ADMINUSER_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 47, 29, 51411, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customer_user_model',
            name='CUSTOMERUSER_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 47, 29, 84418, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='jwt_token_model',
            name='JWTTOKEN_TOKEN_VALUE',
            field=models.CharField(blank=True, default=uuid.UUID('ec4a668d-1d0d-4745-91cf-5d44b10a2793'), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='jwt_token_model',
            name='JWTTOKEN_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 47, 29, 85418, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='medicine_products_model',
            name='MEDICINEPRODUCTS_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 47, 29, 86418, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='medicine_products_prices_model',
            name='MEDICINEPRODUCTSPRICES_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 47, 29, 87419, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='pharmacist_users_model',
            name='PHARMACISTUSERS_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 47, 29, 83418, tzinfo=utc), editable=False),
        ),
        migrations.CreateModel(
            name='PHARMICIST_BIDDING_MODEL',
            fields=[
                ('PHARMICISTBIDDING_INDEX_KEY', models.AutoField(primary_key=True, serialize=False)),
                ('PHARMICISTBIDDING_BID_PRICE', models.CharField(blank=True, max_length=400, null=True)),
                ('CUSTOMERPHARMACIST_Create_Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('CUSTOMERPHARMACIST_Update_Date', models.DateTimeField(default=datetime.datetime(2023, 2, 6, 10, 47, 29, 89419, tzinfo=utc), editable=False)),
                ('CUSTOMERPHARMACIST_isActive', models.BooleanField(default=True)),
                ('PHARMICISTBIDDING_CONTRACT_PROFILE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DATABASE_LAYER.customer_pharmacist_alert_model')),
                ('PHARMICISTBIDDING_PHARMACIST_PROFILE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DATABASE_LAYER.pharmacist_users_model')),
            ],
            options={
                'verbose_name': 'PHARMICIST_BIDDING_MODEL',
            },
        ),
        migrations.AddField(
            model_name='customer_pharmacist_alert_model',
            name='CUSTOMERPHARMACIST_CUSTOMER_PROFILE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DATABASE_LAYER.customer_user_model'),
        ),
    ]
