# Generated by Django 3.2.4 on 2023-02-05 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE_LAYER', '0003_auto_20230205_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmicist_bidding_model',
            name='PHARMICISTBIDDING_BID_MEDICINENAME',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='admin_user_model',
            name='ADMINUSER_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 58, 40, 806950, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customer_pharmacist_alert_model',
            name='CUSTOMERPHARMACIST_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 58, 40, 841957, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customer_user_model',
            name='CUSTOMERUSER_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 58, 40, 837957, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='jwt_token_model',
            name='JWTTOKEN_TOKEN_VALUE',
            field=models.CharField(blank=True, default=uuid.UUID('fe2b1787-de37-4b63-bcf4-7fa1d50859ec'), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='jwt_token_model',
            name='JWTTOKEN_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 58, 40, 838957, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='medicine_products_model',
            name='MEDICINEPRODUCTS_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 58, 40, 839957, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='medicine_products_prices_model',
            name='MEDICINEPRODUCTSPRICES_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 58, 40, 840957, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='pharmacist_users_model',
            name='PHARMACISTUSERS_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 58, 40, 837957, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='pharmicist_bidding_model',
            name='CUSTOMERPHARMACIST_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 11, 58, 40, 842957, tzinfo=utc), editable=False),
        ),
    ]
