# Generated by Django 3.2.4 on 2023-02-05 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DATABASE_LAYER', '0004_auto_20230205_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user_model',
            name='ADMINUSER_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 17, 972932, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customer_pharmacist_alert_model',
            name='CUSTOMERPHARMACIST_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 18, 8940, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='customer_user_model',
            name='CUSTOMERUSER_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 18, 4940, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='jwt_token_model',
            name='JWTTOKEN_TOKEN_VALUE',
            field=models.CharField(blank=True, default=uuid.UUID('aff322c9-ea8e-4809-b5e5-d9b176c5ed74'), max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='jwt_token_model',
            name='JWTTOKEN_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 18, 5941, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='medicine_products_model',
            name='MEDICINEPRODUCTS_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 18, 6940, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='medicine_products_prices_model',
            name='MEDICINEPRODUCTSPRICES_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 18, 7940, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='pharmacist_users_model',
            name='PHARMACISTUSERS_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 18, 3940, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='pharmicist_bidding_model',
            name='CUSTOMERPHARMACIST_Update_Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 18, 8940, tzinfo=utc), editable=False),
        ),
        migrations.CreateModel(
            name='ORDERS_PLACED_MODEL',
            fields=[
                ('ORDERSPLACED_INDEX_KEY', models.AutoField(primary_key=True, serialize=False)),
                ('ORDERSPLACED_DELIVERED', models.BooleanField(default=False)),
                ('ORDERSPLACED_Create_Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ORDERSPLACED_Update_Date', models.DateTimeField(default=datetime.datetime(2023, 2, 6, 13, 0, 18, 10941, tzinfo=utc), editable=False)),
                ('ORDERSPLACED_isActive', models.BooleanField(default=True)),
                ('ORDERSPLACED_BID_PROFILE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DATABASE_LAYER.pharmicist_bidding_model')),
                ('ORDERSPLACED_CONTRACT_PROFILE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DATABASE_LAYER.customer_pharmacist_alert_model')),
            ],
            options={
                'verbose_name': 'ORDERS_PLACED_MODEL',
            },
        ),
    ]
