"""EPHARMACY_API URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from AUTHENTICATION.SIGNUP_API_VIEWS.SIGNUP_CUSTOMER import SIGNUP_CUSTOMER_APIVIEW
from AUTHENTICATION.LOGIN_API_VIEWS.CUSTOMER_LOGIN import LOGIN_CUSTOMER_APIVIEW
from AUTHENTICATION.JWT_API_VIEWS.CUSTOMER_JWT import JWT_CUSTOMER_APIVIEW

from AUTHENTICATION.SIGNUP_API_VIEWS.SIGNUP_PHARMACIST import SIGNUP_PHARMACIST_APIVIEW
from AUTHENTICATION.LOGIN_API_VIEWS.PHARMACIST_LOGIN import LOGIN_PHARMACIST_APIVIEW
from AUTHENTICATION.JWT_API_VIEWS.PHARMACIST_JWT import JWT_PHARMACIST_APIVIEW

from AUTHENTICATION.SIGNUP_API_VIEWS.SIGNUP_ADMIN import SIGNUP_ADMIN_APIVIEW
from AUTHENTICATION.LOGIN_API_VIEWS.ADMIN_LOGIN import LOGIN_ADMIN_APIVIEW
from AUTHENTICATION.JWT_API_VIEWS.ADMIN_JWT import JWT_ADMIN_APIVIEW

from CUSTOMER_MODULE.API_VIEWS.SEARCH_MEDICINE import SEARCH_MEDICINE_VIEW
from CUSTOMER_MODULE.API_VIEWS.SEARCH_BY_SALTS import SEARCH_MEDICINE_BY_SALTS_VIEW
from CUSTOMER_MODULE.API_VIEWS.ALERT_LOCAL_PHARMACISTS import ALERT_LOCAL_PHARMICISTS_VIEW
from CUSTOMER_MODULE.API_VIEWS.GET_BIDS_ON_CONTRACT import GET_BIDS_CONTRACT_VIEW
from CUSTOMER_MODULE.API_VIEWS.PLACE_ORDER import ORDER_PLACED_VIEW
from CUSTOMER_MODULE.API_VIEWS.GET_ALL_ORDERS import ORDERS_ALL_VIEW

from PHARMACIST_MODULE.API_VIEWS.PENDING_ALERTS import PENDING_ALERTS_LOCAL_PHARMICISTS_VIEW
from PHARMACIST_MODULE.API_VIEWS.BID_ON_CONTRACT import BID_CONTRACT_PHARMACIST_VIEW
from PHARMACIST_MODULE.API_VIEWS.GET_PENDING_ORDERS import PENDINGORDERS_PHARMACY_VIEW
from PHARMACIST_MODULE.API_VIEWS.ORDER_STATUS_DELIVERED import ORDER_STATUS_UPDATE_PHARMACY_VIEW
from PHARMACIST_MODULE.API_VIEWS.GET_ALL_ORDERS import ALLORDERS_PHARMACY_VIEW

urlpatterns = [
    path('admin/', admin.site.urls),

    path('CUSTOMER/SIGNUP/', SIGNUP_CUSTOMER_APIVIEW.as_view()),
    path('CUSTOMER/LOGIN/', LOGIN_CUSTOMER_APIVIEW.as_view()),
    path('CUSTOMER/JWT_LOGIN/', JWT_CUSTOMER_APIVIEW.as_view()),
    path('CUSTOMER/SEARCH_MEDICINE/', SEARCH_MEDICINE_VIEW.as_view()),
    path('CUSTOMER/SEARCH_MEDICINE_BY_SALTS/', SEARCH_MEDICINE_BY_SALTS_VIEW.as_view()),
    path('CUSTOMER/MEDICINE_PHARMICIST_ALERT/', ALERT_LOCAL_PHARMICISTS_VIEW.as_view()),
    path('CUSTOMER/BIDS_ON_CONTRACT/', GET_BIDS_CONTRACT_VIEW.as_view()),
    path('CUSTOMER/ORDER_MEDICINE/', ORDER_PLACED_VIEW.as_view()),
    path('CUSTOMER/ORDERS_OF_USER/', ORDERS_ALL_VIEW.as_view()),

    path('PHARMACIST/SIGNUP/', SIGNUP_PHARMACIST_APIVIEW.as_view()),
    path('PHARMACIST/LOGIN/', LOGIN_PHARMACIST_APIVIEW.as_view()),
    path('PHARMACIST/JWT_LOGIN/', JWT_PHARMACIST_APIVIEW.as_view()),
    path('PHARMACIST/PENDING_ALERTS/', PENDING_ALERTS_LOCAL_PHARMICISTS_VIEW.as_view()),
    path('PHARMACIST/BID_CONTRACT/', BID_CONTRACT_PHARMACIST_VIEW.as_view()),
    path('PHARMACIST/PENDING_ORDERS/', PENDINGORDERS_PHARMACY_VIEW.as_view()),
    path('PHARMACIST/ORDER_DELIVERED/', ORDER_STATUS_UPDATE_PHARMACY_VIEW.as_view()),
    path('PHARMACIST/ORDERS_BY_PHARMACY/', ALLORDERS_PHARMACY_VIEW.as_view()),

    path('ADMIN/SIGNUP/', SIGNUP_ADMIN_APIVIEW.as_view()),
    path('ADMIN/LOGIN/', LOGIN_ADMIN_APIVIEW.as_view()),
    path('ADMIN/JWT_LOGIN/', JWT_ADMIN_APIVIEW.as_view()),
]
